const CFG = window.TIMZY_CONFIG || {};
const fallbackProducts = [
  {name:'Premium White Agbada',category:'Agbada',price:'120000',description:'Luxury agbada with clean embroidery and premium finish.',images:['assets/hero-agbada-white.jpg','assets/real-agbada-white-gold.jpg']},
  {name:'Grey Senator Wear',category:'Senator',price:'70000',description:'Modern senator style for confident everyday elegance.',images:['assets/real-senator-grey.jpg']},
  {name:'Luxury Fabric Stack',category:'Fabrics',price:'25000',description:'Premium fabrics for custom sewing and special occasions.',images:['assets/real-fabrics-stack.jpg','assets/real-fabric-market.jpg']},
  {name:'Cream Agbada',category:'Agbada',price:'110000',description:'Clean cream agbada for weddings and celebrations.',images:['assets/real-agbada-cream.jpg']}
];
let products=[],activeCat='All',currentProduct=null,currentIndex=0;
function money(v){const n=Number(String(v||'').replace(/[^0-9.]/g,''));return n?`${CFG.currency||'₦'}${n.toLocaleString()}`:(v||'Price on request')}
function csvParse(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(cell||row.length){row.push(cell);rows.push(row);row=[];cell=''}if(c==='\r'&&n==='\n')i++;continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function get(row,keys){for(const k of keys){const found=Object.keys(row).find(h=>h.toLowerCase().trim()===k.toLowerCase());if(found&&row[found])return row[found]}return ''}
function driveImage(url){if(!url)return '';const m=String(url).match(/[-\w]{25,}/);return m?`https://drive.google.com/thumbnail?id=${m[0]}&sz=w1000`:url}
function splitImages(v){return String(v||'').split(/[\n,;]/).map(s=>driveImage(s.trim())).filter(Boolean)}
function normalize(row){const images=[...splitImages(get(row,['Images','Image','Photo','Photos','Product Images','Upload product images'])),...['Image 1','Image1','Image 2','Image2','Image 3','Image3','Image 4','Image4','Image 5','Image5'].map(k=>driveImage(get(row,[k]))).filter(Boolean)];return {name:get(row,['Product Name','Name','Product','Item'])||'Untitled Product',category:get(row,['Category','Product Category'])||'Collection',price:get(row,['Price','Amount','Selling Price'])||'',description:get(row,['Description','Product Description','Notes'])||'',status:get(row,['Status','Availability'])||'Active',images:images.length?images:['assets/timzy-logo.png']}}
async function loadProducts(){try{if(CFG.productSheetCsvUrl){const res=await fetch(CFG.productSheetCsvUrl,{cache:'no-store'});const csv=await res.text();const rows=csvParse(csv);const headers=rows.shift().map(h=>h.trim());products=rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||'']))).map(normalize).filter(p=>!String(p.status).toLowerCase().includes('hidden'))}else products=fallbackProducts}catch(e){console.warn(e);products=fallbackProducts}renderChips();renderCatalog()}
function renderChips(){const cats=['All',...new Set(products.map(p=>p.category).filter(Boolean))];categoryChips.innerHTML=cats.map(c=>`<button class="chip ${c===activeCat?'active':''}" onclick="activeCat='${c.replace(/'/g,"\\'")}';renderChips();renderCatalog()">${c}</button>`).join('')}
function renderCatalog(){const list=activeCat==='All'?products:products.filter(p=>p.category===activeCat);catalogGrid.innerHTML=list.length?list.map((p,i)=>`<article class="product-card product-card-v2" onclick="openProduct(${products.indexOf(p)})"><div class="product-img product-img-v2"><img loading="lazy" src="${p.images[0]}" alt="${p.name}"></div><div class="product-info product-info-v2"><span>${p.category}</span><h3>${p.name}</h3><div class="price">${money(p.price)}</div></div></article>`).join(''):'<div class="empty">No products found.</div>'}
function setModalImg(i){if(!currentProduct)return;currentIndex=(i+currentProduct.images.length)%currentProduct.images.length;modalImage.src=currentProduct.images[currentIndex];modalThumbs.innerHTML=currentProduct.images.map((im,idx)=>`<img class="${idx===currentIndex?'active':''}" src="${im}" onclick="setModalImg(${idx})">`).join('')}
function openProduct(i){currentProduct=products[i];currentIndex=0;modalName.textContent=currentProduct.name;modalCategory.textContent=currentProduct.category;modalPrice.textContent=money(currentProduct.price);modalDesc.textContent=currentProduct.description||'Contact Timzy Fashion for measurements, sizing and availability.';modalWhatsapp.href=`https://wa.me/${CFG.whatsappNumber}?text=${encodeURIComponent('Hello Timzy Fashion, I am interested in '+currentProduct.name)}`;setModalImg(0);productModal.classList.add('open')}
function closeProduct(){productModal.classList.remove('open')}function nextImg(){setModalImg(currentIndex+1)}function prevImg(){setModalImg(currentIndex-1)}
window.openProduct=openProduct;window.closeProduct=closeProduct;window.nextImg=nextImg;window.prevImg=prevImg;window.setModalImg=setModalImg;loadProducts();

if(document.getElementById('bottomWhatsApp')){bottomWhatsApp.href=`https://wa.me/${CFG.whatsappNumber||''}?text=${encodeURIComponent('Hello Timzy Fashion, I would like to make an enquiry.')}`;}
