import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getFirestore, collection, addDoc, getDocs, query, orderBy, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const CFG=window.TIMZY_CONFIG||{};const app=initializeApp(CFG.firebaseConfig);const auth=getAuth(app);const db=getFirestore(app);
function money(v){const n=Number(String(v||0).replace(/[^0-9.]/g,''));return `${CFG.currency||'₦'}${(n||0).toLocaleString()}`}
function msg(t){const el=document.getElementById('loginMsg'); if(el) el.textContent=t}
window.login=async()=>{try{await signInWithEmailAndPassword(auth,email.value,password.value);location.href='admin/index.html'}catch(e){msg(e.message.replace('Firebase: ',''))}}
if(location.pathname.includes('/admin/')){onAuthStateChanged(auth,u=>{if(!u) location.href='../login.html'; else loadAdminData()})}
const fallbackProducts=[{name:'Premium White Agbada',category:'Agbada',price:'120000',images:['../assets/hero-agbada-white.jpg']},{name:'Grey Senator Wear',category:'Senator',price:'70000',images:['../assets/real-senator-grey.jpg']}];
function csvParse(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(cell||row.length){row.push(cell);rows.push(row);row=[];cell=''}if(c==='\r'&&n==='\n')i++;continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function get(row,keys){for(const k of keys){const f=Object.keys(row).find(h=>h.toLowerCase().trim()===k.toLowerCase());if(f&&row[f])return row[f]}return ''}
function driveImage(url){if(!url)return '';const m=String(url).match(/[-\w]{25,}/);return m?`https://drive.google.com/thumbnail?id=${m[0]}&sz=w1000`:url}
function splitImages(v){return String(v||'').split(/[\n,;]/).map(s=>driveImage(s.trim())).filter(Boolean)}
function normalize(row){const imgs=[...splitImages(get(row,['Images','Image','Photo','Photos','Product Images','Upload product images'])),...['Image 1','Image1','Image 2','Image2','Image 3','Image3'].map(k=>driveImage(get(row,[k]))).filter(Boolean)];return {name:get(row,['Product Name','Name','Product','Item'])||'Untitled',category:get(row,['Category'])||'Collection',price:get(row,['Price','Amount','Selling Price'])||'',images:imgs.length?imgs:['../assets/timzy-logo.png']}}
async function loadSheet(url){if(!url)return null;const res=await fetch(url,{cache:'no-store'});const rows=csvParse(await res.text());const h=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]||''])))}
async function loadProducts(){try{const rows=await loadSheet(CFG.productSheetCsvUrl);return rows?rows.map(normalize):fallbackProducts}catch(e){console.warn(e);return fallbackProducts}}
async function loadFirestore(name){try{const snap=await getDocs(query(collection(db,name),orderBy('createdAt','desc')));return snap.docs.map(d=>({id:d.id,...d.data()}))}catch(e){console.warn(e);return []}}
function rowsSales(items,target){target.innerHTML=items.length?items.map(s=>`<tr><td>${s.date||''}</td><td>${s.customer||''}</td><td>${s.product||''}</td><td>${money(s.amount)}</td><td>${s.method||''}</td></tr>`).join(''):'<tr><td colspan="5">No records yet.</td></tr>'}
function rowsExpenses(items,target){target.innerHTML=items.length?items.map(x=>`<tr><td>${x.date||''}</td><td>${x.title||''}</td><td>${x.category||''}</td><td>${money(x.amount)}</td></tr>`).join(''):'<tr><td colspan="4">No records yet.</td></tr>'}
window.loadAdminData=async()=>{const products=await loadProducts();const sales=await loadFirestore('sales');const expenses=await loadFirestore('expenses');const salesTotal=sales.reduce((a,b)=>a+Number(b.amount||0),0);const expTotal=expenses.reduce((a,b)=>a+Number(b.amount||0),0);kProducts.textContent=products.length;kSales.textContent=money(salesTotal);kExpenses.textContent=money(expTotal);kProfit.textContent=money(salesTotal-expTotal);recentSales&&rowsSales(sales.slice(0,6),recentSales);salesRows&&rowsSales(sales,salesRows);expenseRows&&rowsExpenses(expenses,expenseRows);if(adminProducts)adminProducts.innerHTML=products.map(p=>`<article class="product-card"><div class="product-img"><img src="${p.images[0]}" alt="${p.name}"></div><div class="product-info"><h3>${p.name}</h3><div class="price">${money(p.price)}</div><div class="meta">${p.category}</div></div></article>`).join('');for(const id of ['productFormBtn','productFormBtn2']){const e=document.getElementById(id);if(e)e.href=CFG.productFormUrl||'#'}for(const id of ['sheetBtn','sheetBtn2']){const e=document.getElementById(id);if(e)e.href=CFG.productSheetUrl||'#'}};
function showTab(tab){document.querySelectorAll('.admin-tab').forEach(s=>s.hidden=s.id!==tab);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));pageTitle.textContent=tab[0].toUpperCase()+tab.slice(1)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)showTab(b.dataset.tab)});
document.getElementById('logoutBtn')?.addEventListener('click',async()=>{await signOut(auth);location.href='../login.html'});
document.getElementById('saleForm')?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());data.amount=Number(data.amount||0);data.date=new Date().toLocaleDateString();data.createdAt=serverTimestamp();await addDoc(collection(db,'sales'),data);e.target.reset();loadAdminData();alert('Sale saved')});
document.getElementById('expenseForm')?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());data.amount=Number(data.amount||0);data.date=new Date().toLocaleDateString();data.createdAt=serverTimestamp();await addDoc(collection(db,'expenses'),data);e.target.reset();loadAdminData();alert('Expense saved')});
