const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const money=n=>`₦${Number(n||0).toLocaleString()}`; const today=()=>new Date().toISOString().slice(0,10);
const store={get:k=>JSON.parse(localStorage.getItem('timzy_'+k)||'[]'),set:(k,v)=>localStorage.setItem('timzy_'+k,JSON.stringify(v))};
function guard(){if(!localStorage.getItem('timzy_staff') && !location.pathname.endsWith('/login.html')){} }
function cfg(){return window.TIMZY_CONFIG||{}}
function fillLinks(){document.querySelectorAll('[data-form-link]').forEach(a=>a.href=cfg().productFormUrl||'#');document.querySelectorAll('[data-sheet-link]').forEach(a=>a.href=cfg().productSheetUrl||'#')}
function nav(){const m=$('.menu'),s=$('.sidebar'); if(m&&s)m.onclick=()=>s.classList.toggle('open'); const path=location.pathname.split('/').pop()||'index.html'; $$('[data-page]').forEach(a=>a.classList.toggle('active',a.dataset.page===path));}
function logout(){localStorage.removeItem('timzy_staff');location.href='../login.html'}
function seed(){if(!store.get('sales').length)store.set('sales',[{date:today(),customer:'Walk-in Customer',product:'Premium Senator',amount:185000,method:'Transfer',notes:'Demo sale'}]); if(!store.get('expenses').length)store.set('expenses',[{date:today(),title:'Fabric purchase',category:'Materials',amount:35000,notes:'Demo expense'}]);}
function totals(){const sales=store.get('sales'),expenses=store.get('expenses'); const t=today(); const todaySales=sales.filter(x=>x.date===t).reduce((a,b)=>a+Number(b.amount||0),0); const todayExp=expenses.filter(x=>x.date===t).reduce((a,b)=>a+Number(b.amount||0),0); return {sales,expenses,todaySales,todayExp,profit:todaySales-todayExp};}
function dashboard(){if(!$('#kpiSales'))return; const t=totals(); $('#kpiSales').textContent=money(t.todaySales); $('#kpiExpenses').textContent=money(t.todayExp); $('#kpiProfit').textContent=money(t.profit); $('#kpiOrders').textContent=t.sales.filter(x=>x.date===today()).length; const activity=[...t.sales.map(x=>({type:'Sale',title:x.product,amount:x.amount,date:x.date})),...t.expenses.map(x=>({type:'Expense',title:x.title,amount:x.amount,date:x.date}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,8); $('#activityRows').innerHTML=activity.map(x=>`<tr><td>${x.date}</td><td><span class="pill">${x.type}</span></td><td>${x.title}</td><td>${money(x.amount)}</td></tr>`).join('')||'<tr><td colspan="4">No activity yet.</td></tr>';}
function salesPage(){const f=$('#saleForm'); if(!f)return; const draw=()=>{$('#salesRows').innerHTML=store.get('sales').slice().reverse().map((x,i)=>`<tr><td>${x.date}</td><td>${x.customer}</td><td>${x.product}</td><td>${money(x.amount)}</td><td>${x.method}</td><td><button class="btn" onclick="deleteSale(${store.get('sales').length-1-i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No sales yet.</td></tr>'}; f.date.value=today(); f.onsubmit=e=>{e.preventDefault(); const fd=new FormData(f); const arr=store.get('sales'); arr.push(Object.fromEntries(fd)); store.set('sales',arr); f.reset(); f.date.value=today(); draw();}; window.deleteSale=i=>{const a=store.get('sales');a.splice(i,1);store.set('sales',a);draw()}; draw();}
function expensesPage(){const f=$('#expenseForm'); if(!f)return; const draw=()=>{$('#expenseRows').innerHTML=store.get('expenses').slice().reverse().map((x,i)=>`<tr><td>${x.date}</td><td>${x.title}</td><td>${x.category}</td><td>${money(x.amount)}</td><td><button class="btn" onclick="deleteExpense(${store.get('expenses').length-1-i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5">No expenses yet.</td></tr>'}; f.date.value=today(); f.onsubmit=e=>{e.preventDefault(); const fd=new FormData(f); const arr=store.get('expenses'); arr.push(Object.fromEntries(fd)); store.set('expenses',arr); f.reset(); f.date.value=today(); draw();}; window.deleteExpense=i=>{const a=store.get('expenses');a.splice(i,1);store.set('expenses',a);draw()}; draw();}
async function productsPage(){const el=$('#productRows'); if(!el)return; const products=await fetch('../data/products.json').then(r=>r.json()).catch(()=>[]); el.innerHTML=products.slice(0,30).map(p=>`<tr><td>${p.sku||p.id}</td><td>${p.name}</td><td>${p.category}</td><td>${money(p.price)}</td><td><span class="pill">${p.status||'Published'}</span></td></tr>`).join('')||'<tr><td colspan="5">No products found.</td></tr>'; $('#productCount')&&($('#productCount').textContent=products.length);}
function reportsPage(){if(!$('#reportRows'))return; const t=totals(); $('#rSales').textContent=money(t.todaySales); $('#rExpenses').textContent=money(t.todayExp); $('#rProfit').textContent=money(t.profit); $('#reportRows').innerHTML=[...t.sales.map(x=>({date:x.date,type:'Sale',title:x.product,amount:x.amount})),...t.expenses.map(x=>({date:x.date,type:'Expense',title:x.title,amount:x.amount}))].map(x=>`<tr><td>${x.date}</td><td>${x.type}</td><td>${x.title}</td><td>${money(x.amount)}</td></tr>`).join('')||'<tr><td colspan="4">No records yet.</td></tr>'; window.exportCsv=()=>{const rows=[['date','type','title','amount'],...$$('#reportRows tr').map(tr=>$$('td',tr).map(td=>td.textContent))]; const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download='timzy-report.csv'; a.click();};}
window.addEventListener('DOMContentLoaded',()=>{guard();seed();nav();fillLinks();dashboard();salesPage();expensesPage();productsPage();reportsPage();});
