const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const money=n=>`₦${Number(String(n||0).replace(/[^0-9.-]/g,'')||0).toLocaleString()}`; const today=()=>new Date().toISOString().slice(0,10);
const store={get:k=>JSON.parse(localStorage.getItem('timzy_'+k)||'[]'),set:(k,v)=>localStorage.setItem('timzy_'+k,JSON.stringify(v))};
function cfg(){return window.TIMZY_CONFIG||{}}
function fillLinks(){document.querySelectorAll('[data-form-link]').forEach(a=>a.href=cfg().productFormUrl||'#');document.querySelectorAll('[data-sheet-link]').forEach(a=>a.href=cfg().productSheetUrl||'#')}
function nav(){const m=$('.menu'),s=$('.sidebar'); if(m&&s)m.onclick=()=>s.classList.toggle('open'); const path=location.pathname.split('/').pop()||'index.html'; $$('[data-page]').forEach(a=>a.classList.toggle('active',a.dataset.page===path));}
function logout(){localStorage.removeItem('timzy_staff');location.href='../login.html'}
function seed(){if(!store.get('sales').length)store.set('sales',[{date:today(),customer:'Walk-in Customer',product:'Premium Senator',amount:185000,method:'Transfer',notes:'Demo sale'}]); if(!store.get('expenses').length)store.set('expenses',[{date:today(),title:'Fabric purchase',category:'Materials',amount:35000,notes:'Demo expense'}]);}
async function loadBaseProducts(){try{return await fetch('../data/products.json',{cache:'no-store'}).then(r=>r.json())}catch{return []}}
async function getAdminProducts(){const local=localStorage.getItem('timzy_products'); if(local) return JSON.parse(local); const base=await loadBaseProducts(); store.set('products',base); return base;}
function productImages(p){return [p.image1,p.image2,p.image3].filter(Boolean)}
function totals(){const sales=store.get('sales'),expenses=store.get('expenses'),orders=JSON.parse(localStorage.getItem('timzy_orders')||'[]'); const t=today(); const todaySales=sales.filter(x=>x.date===t).reduce((a,b)=>a+Number(b.amount||0),0); const todayExp=expenses.filter(x=>x.date===t).reduce((a,b)=>a+Number(b.amount||0),0); return {sales,expenses,orders,todaySales,todayExp,profit:todaySales-todayExp};}
function dashboard(){if(!$('#kpiSales'))return; const t=totals(); $('#kpiSales').textContent=money(t.todaySales); $('#kpiExpenses').textContent=money(t.todayExp); $('#kpiProfit').textContent=money(t.profit); $('#kpiOrders').textContent=(t.orders.length||t.sales.filter(x=>x.date===today()).length); const activity=[...t.orders.map(x=>({type:'Order',title:x.customer||'Customer order',amount:x.total,date:(x.date||'').slice(0,10)})),...t.sales.map(x=>({type:'Sale',title:x.product,amount:x.amount,date:x.date})),...t.expenses.map(x=>({type:'Expense',title:x.title,amount:x.amount,date:x.date}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,10); $('#activityRows').innerHTML=activity.map(x=>`<tr><td>${x.date}</td><td><span class="pill">${x.type}</span></td><td>${x.title}</td><td>${money(x.amount)}</td></tr>`).join('')||'<tr><td colspan="4">No activity yet.</td></tr>';}
function salesPage(){const f=$('#saleForm'); if(!f)return; const draw=()=>{$('#salesRows').innerHTML=store.get('sales').slice().reverse().map((x,i)=>`<tr><td>${x.date}</td><td>${x.customer}</td><td>${x.product}</td><td>${money(x.amount)}</td><td>${x.method}</td><td><button class="btn small danger" onclick="deleteSale(${store.get('sales').length-1-i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No sales yet.</td></tr>'}; f.date.value=today(); f.onsubmit=e=>{e.preventDefault(); const arr=store.get('sales'); arr.push(Object.fromEntries(new FormData(f))); store.set('sales',arr); f.reset(); f.date.value=today(); draw();}; window.deleteSale=i=>{const a=store.get('sales');a.splice(i,1);store.set('sales',a);draw()}; draw();}
function expensesPage(){const f=$('#expenseForm'); if(!f)return; const draw=()=>{$('#expenseRows').innerHTML=store.get('expenses').slice().reverse().map((x,i)=>`<tr><td>${x.date}</td><td>${x.title}</td><td>${x.category}</td><td>${money(x.amount)}</td><td><button class="btn small danger" onclick="deleteExpense(${store.get('expenses').length-1-i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5">No expenses yet.</td></tr>'}; f.date.value=today(); f.onsubmit=e=>{e.preventDefault(); const arr=store.get('expenses'); arr.push(Object.fromEntries(new FormData(f))); store.set('expenses',arr); f.reset(); f.date.value=today(); draw();}; window.deleteExpense=i=>{const a=store.get('expenses');a.splice(i,1);store.set('expenses',a);draw()}; draw();}
async function productsPage(){const el=$('#productRows'); if(!el)return; let products=await getAdminProducts(); const save=()=>store.set('products',products); const draw=()=>{ if($('#productCount')) $('#productCount').textContent=products.filter(p=>p.status!=='Deleted').length; el.innerHTML=products.filter(p=>p.status!=='Deleted').map((p,i)=>`<tr><td><img class="product-thumb" src="${(productImages(p)[0]||'../assets/img/hero-man.jpg').replace('assets/','../assets/')}" onerror="this.src='../assets/img/hero-man.jpg'"></td><td>${p.sku||p.id}</td><td>${p.name}</td><td>${p.category}</td><td>${money(p.price)}</td><td><span class="pill">${p.status||'Published'}</span></td><td><div class="actions"><button class="btn small" onclick="editProduct('${p.id}')">Edit</button><button class="btn small" onclick="duplicateProduct('${p.id}')">Duplicate</button><button class="btn small danger" onclick="deleteProduct('${p.id}')">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="7">No products found.</td></tr>'; };
 const modal=$('#productModal'), form=$('#productForm'); const open=()=>modal?.classList.add('open'); const close=()=>modal?.classList.remove('open'); $('#closeProductModal')?.addEventListener('click',close); $('#addProductBtn')?.addEventListener('click',()=>{form.reset(); form.id.value='tf-'+Date.now(); $('#modalTitle').textContent='Add Product'; open();});
 window.editProduct=id=>{const p=products.find(x=>String(x.id)===String(id)); if(!p)return; $('#modalTitle').textContent='Edit Product'; Object.keys(Object.fromEntries(new FormData(form))).forEach(k=>{if(form.elements[k]) form.elements[k].value=p[k]||''}); form.id.value=p.id; open();};
 window.duplicateProduct=id=>{const p=products.find(x=>String(x.id)===String(id)); if(!p)return; const copy={...p,id:'tf-copy-'+Date.now(),sku:(p.sku||'TF')+'-COPY',name:p.name+' Copy'}; products.push(copy); save(); draw();};
 window.deleteProduct=id=>{if(!confirm('Delete this product from the storefront preview?'))return; products=products.map(p=>String(p.id)===String(id)?{...p,status:'Deleted'}:p); save(); draw();};
 form?.addEventListener('submit',e=>{e.preventDefault(); const data=Object.fromEntries(new FormData(form)); const idx=products.findIndex(p=>String(p.id)===String(data.id)); const clean={...data,price:Number(data.price||0),featured:false,deliveryEstimate:'7–14 working days'}; if(idx>=0) products[idx]={...products[idx],...clean}; else products.push(clean); save(); close(); draw();}); draw();}
function reportsPage(){if(!$('#reportRows'))return; const t=totals(); $('#rSales').textContent=money(t.todaySales); $('#rExpenses').textContent=money(t.todayExp); $('#rProfit').textContent=money(t.profit); $('#reportRows').innerHTML=[...t.orders.map(x=>({date:(x.date||'').slice(0,10),type:'Order',title:x.customer,amount:x.total})),...t.sales.map(x=>({date:x.date,type:'Sale',title:x.product,amount:x.amount})),...t.expenses.map(x=>({date:x.date,type:'Expense',title:x.title,amount:x.amount}))].map(x=>`<tr><td>${x.date}</td><td>${x.type}</td><td>${x.title}</td><td>${money(x.amount)}</td></tr>`).join('')||'<tr><td colspan="4">No records yet.</td></tr>'; window.exportCsv=()=>{const rows=[['date','type','title','amount'],...$$('#reportRows tr').map(tr=>$$('td',tr).map(td=>td.textContent))]; const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download='timzy-report.csv'; a.click();};}
window.addEventListener('DOMContentLoaded',()=>{seed();nav();fillLinks();dashboard();salesPage();expensesPage();productsPage();reportsPage();});
